# Generated by Django 2.1.1 on 2018-10-19 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('photo', models.ImageField(upload_to='')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('size', models.IntegerField()),
                ('category', models.CharField(max_length=100)),
                ('code', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
