# Generated by Django 2.1.1 on 2018-11-12 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KingsMan', '0003_productphoto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productphoto',
            name='code',
        ),
        migrations.DeleteModel(
            name='productPhoto',
        ),
    ]
