# Generated by Django 2.1.1 on 2018-11-12 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('KingsMan', '0004_auto_20181112_1524'),
    ]

    operations = [
        migrations.CreateModel(
            name='productPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='')),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KingsMan.product')),
            ],
        ),
    ]
