# Generated by Django 2.1.1 on 2018-11-27 12:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('KingsMan', '0006_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='userName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
