# Generated by Django 2.1.1 on 2018-11-27 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KingsMan', '0007_auto_20181127_2152'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='amount',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
